modLoader="javafml"
loaderVersion="[4,)"
license="All rights reserved"
issueTrackerURL="https://github.com/yourname/flymod/issues"
[[mods]]
modId="flymod"
version="${file.jarVersion}"
displayName="Fly Mod"
logoFile="flymod.png"
credits="Thanks to the Minecraft Forge community"
authors="YourName"
description='''
A simple mod that allows toggling fly mode with the H key.
'''
[[dependencies.flymod]]
    modId="forge"
    mandatory=true
    versionRange="[58.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.flymod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.8,1.22)"
    ordering="NONE"
    side="BOTH"
